<?php
ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(E_ALL);

define('SHORT_TIME_FORMAT', 'n-j-Y');
define('TIME_FORMAT', 'n-j-Y g:i A');
define('DEFAULT_TIME_FORMAT', 'Y-m-d H:i'); // the time format required by the default value of the datepicker
define('PREVIEW_NUMBER', 5);

define('HELP_EMAIL', 'croma@chapresearch.com');

define('ALLOWED_TAGS', '<em><b><strong><u>');

define('NUM_RECENT_OUTREACHES_SHOWN', 8);
define('NUM_UPCOMING_OUTREACHES_SHOWN', 5);

?>