<?php
/**
 * @file
 * This is the main module file.
 */

$upOne = realpath(dirname(__FILE__) . '/..');
include_once($upOne.'/includePaths.inc');
include_once(MODULES_FOLDER."/blockSupport.php");

global $themeCustomizationBlockInfo;
global $themeCustomizationBlockViewFns;

$themeCustomizationBlockInfo = array();
$themeCustomizationBlockViewFns = array();

include_once("themeCustomization_display.php");

/*
  Implements hook_help().
*/
function themeCustomization_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The themeCustomization module manages themeCustomization in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function themeCustomization_block_info()
{
    global $themeCustomizationBlockInfo;

    return($themeCustomizationBlockInfo);
}

//
// hook in the blocks
//
function themeCustomization_block_view($delta = '')
{
    global $themeCustomizationBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$themeCustomizationBlockViewFns)) {
      $themeCustomizationBlockViewFns[$delta]($block);
    }

       return $block;
}
?>

