<?php
/**
 * @file
 * This is the main module file.
 */

include_once("widgets.inc");
include_once(MODULES_FOLDER."/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $widgetsBlockInfo;
global $widgetsBlockViewFns;

$widgetsBlockInfo = array();
$widgetsBlockViewFns = array();

include_once("widgets_display.php");

/*
  Implements hook_help().
*/
function widgets_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The widgets module manages widgets in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function widgets_block_info()
{
    global $widgetsBlockInfo;

    return($widgetsBlockInfo);
}

//
// hook in the blocks
//
function widgets_block_view($delta = '')
{
    global $widgetsBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$widgetsBlockViewFns)) {
      $widgetsBlockViewFns[$delta]($block);
    }

       return $block;
}

function widgets_menu() {
  $items['approveIdea'] = array(
				  'page callback' => 'approveIdea',
				  'page arguments' => array(1),
				  'access callback' => 'hasPermissionForTeam',
				  'access arguments' => array('approveIdeas', 2),
				  'type' => MENU_CALLBACK,
				  );
  return $items;
}
?>