<?php
/**
 * @file
 * This is the main module file.
 */

include_once("notifications.inc");
$upOne = realpath(dirname(__FILE__) . '/..');
include_once($upOne.'/includePaths.inc');
include_once(MODULES_FOLDER."/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $notificationsBlockInfo;
global $notificationsBlockViewFns;

$notificationsBlockInfo = array();
$notificationsBlockViewFns = array();

include_once("notifications_display.php");

/*
  Implements hook_help().
*/
function notifications_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The notification module manages notifications in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function notifications_block_info()
{
  global $notificationsBlockInfo;

  return($notificationsBlockInfo);
}

//
// hook in the blocks
//
function notifications_block_view($delta = '')
{
    global $notificationsBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$notificationsBlockViewFns)) {
      $notificationsBlockViewFns[$delta]($block);
    }

    return $block;
}

function notifications_menu() {
  $items['deleteNotification'] = array(
				  'page callback' => 'deleteNotification',
				  'page arguments' => array(1, 2),
				  'access callback' => TRUE,
  				  'type' => MENU_CALLBACK,
				  );

  $items['dismissNotification'] = array(
				  'page callback' => 'dismissNotification',
				  'page arguments' => array(1),
				  'access callback' => 'isMyNotification',
                                  'access arguments' => array(1),
				  'type' => MENU_CALLBACK,
				  );

  $items['dismissAllNotifications'] = array(
				  'page callback' => 'dismissAllNotifications',
				  'access callback' => TRUE,
				  'type' => MENU_CALLBACK,
				  );
  return $items;
}

?>