<?php
/**
 * @file
 * This is the main module file.
 */

include_once("hourLogging.inc");
include_once("/var/www-croma/croma_modules/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $hourLoggingBlockInfo;
global $hourLoggingBlockViewFns;

$hourLoggingBlockInfo = array();
$hourLoggingBlockViewFns = array();

include_once("philipDisplay.php");
include_once("display.php");

/*
  Implements hook_help().
*/
function hourLogging_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The hour logging module manages hour logging in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function hourLogging_block_info()
{
    global $hourLoggingBlockInfo;

    return($hourLoggingBlockInfo);
}

//
// hook in the blocks
//
function hourLogging_block_view($delta = '')
{
    global $hourLoggingBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$hourLoggingBlockViewFns)) {
      $hourLoggingBlockViewFns[$delta]($block);
    }

    return $block;
}

function hourLogging_permission() {
  return array(
	       'access current_posts content' => array(
						       'title' => t('Access content for the Current posts module'),
						       )
	       );
}

?>