<?php
/**
 * @file
 * This is the main module file.
 */

include_once("users.inc");
include_once("/var/www-croma/croma_modules/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $usersBlockInfo;
global $usersBlockViewFns;

$usersBlockInfo = array();
$usersBlockViewFns = array();

include_once("shreyDisplay.php");
include_once("display.php");

/*
  Implements hook_help().
*/
function users_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The hour logging module manages hour logging in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function users_block_info()
{
    global $usersBlockInfo;

    return($usersBlockInfo);
}

//
// hook in the blocks
//
function users_block_view($delta = '')
{
    global $usersBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$usersBlockViewFns)) {
      $usersBlockViewFns[$delta]($block);
    }

    return $block;
}

?>