<?php
/**
 * @file
 * This is the main module file.
 */

$upOne = realpath(dirname(__FILE__) . '/..');
include_once($upOne.'/includePaths.inc');
include_once(MODULES_FOLDER."/blockSupport.php");

global $adminFunctionsBlockInfo;
global $adminFunctionsBlockViewFns;

$adminFunctionsBlockInfo = array();
$adminFunctionsBlockViewFns = array();

include_once("adminFunctions_display.php");

/*
  Implements hook_help().
*/
function adminFunctions_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The adminFunctions module manages adminFunctions in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function adminFunctions_block_info()
{
    global $adminFunctionsBlockInfo;

    return($adminFunctionsBlockInfo);
}

//
// hook in the blocks
//
function adminFunctions_block_view($delta = '')
{
    global $adminFunctionsBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$adminFunctionsBlockViewFns)) {
      $adminFunctionsBlockViewFns[$delta]($block);
    }

       return $block;
}


function adminFunctions_menu() {
  $items['approveTeam/%'] = array(
				  'page callback' => 'approveTeam',
				  'page arguments' => array(1),
				  'access callback' => 'isAdmin', // admin role in drupal
				  'type' => MENU_CALLBACK,
				  );

  $items['rejectTeam/%'] = array(
				  'page callback' => 'rejectTeam',
				  'page arguments' => array(1),
				  'access callback' => 'isAdmin', // admin role in drupal
				  'type' => MENU_CALLBACK,
				  );
  return $items;
}

function adminFunctions_mail($key, &$message, $params)
{
  $message['body'] = generateMailHeader();  

  switch($key) {
  case 'teamApproved':
    $message['subject'] = "Your Team Has Been Approved!";
    $message['body'] .= "Dear {$params['fullName']},<br>";
    $message['body'] .= "Your team \"{$params['teamName']}\" has been approved for CROMA. You can now enter old hours for your team and start inviting and accepting users!<br><br>";
    $message['body'] .= "Sincerely,<br>";
    $message['body'] .= "The CROMA Team";
    break;
  case 'teamRejected':
    $message['subject'] = "Your Team Creation Request on CROMA Has Been Denied";
    $message['body'] .= "Dear {$params['fullName']},<br>";
    $message['body'] .= "Your team \"{$params['teamName']}\" has been deemed to be either inappropriate or nonexisteant by CROMA staff. If you believe this decision was made in error or would like more information, please email ".HELP_EMAIL.'.<br><br>';
    $message['body'] .= "Sincerely,";
    $message['body'] .= "The CROMA Team";
    break;
  }

  $message['body'] .= generateMailFooter();
}

?>

