<?php
/**
 * @file
 * This is the main module file.
 */

include_once("media.inc");
include_once("/var/www-croma/croma_modules/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $mediaBlockInfo;
global $medaBlockViewFns;

$mediaBlockInfo = array();
$mediaBlockViewFns = array();

include_once("display.php");

/*
  Implements hook_help().
*/
function media_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The media module manages media in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function media_block_info()
{
    global $mediaBlockInfo;

    return($mediaBlockInfo);
}

//
// hook in the blocks
//
function media_block_view($delta = '')
{
    global $mediaBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$mediaBlockViewFns)) {
        $mediaBlockViewFns[$delta]($block);
    }

    return $block;
}

?>