<?php
/**
 * @file
 * This is the main module file.
 */

include_once("hourLogging.inc");
$upOne = realpath(dirname(__FILE__) . '/..');
include_once($upOne.'/includePaths.inc');
include_once(MODULES_FOLDER."/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $hourLoggingBlockInfo;
global $hourLoggingBlockViewFns;

$hourLoggingBlockInfo = array();
$hourLoggingBlockViewFns = array();

include_once("hourLogging_display.php");

/*
  Implements hook_help().
*/
function hourLogging_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The hour logging module manages hour logging in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function hourLogging_block_info()
{
    global $hourLoggingBlockInfo;

    return($hourLoggingBlockInfo);
}

//
// hook in the blocks
//
function hourLogging_block_view($delta = '')
{
    global $hourLoggingBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$hourLoggingBlockViewFns)) {
      $hourLoggingBlockViewFns[$delta]($block);
    }

    return $block;
}

/* canEditHours() - returns whether the user can edit the given hours. Needs the OID to check if the outreach belongs to the given user.*/
function canEditHours($HID)
{
  $OID = dbGetOIDForHours($HID);

  if (canEditHoursForOutreach($OID)){
    return true;
  }

  // is editing own hours
  if(!empty($HID) && isMyHours($HID)){
    return true;
  }

  return false;
}

function canEditHoursForOutreach($OID)
{
  // has permissions or is editing own outreach
  return (isMyOutreach($OID) || hasPermissionForTeam('editAnyHours',dbGetTeamForOutreach($OID)));
}


/* canApproveHours() - returns whether the user can approve the given hours.
 */
function canApproveHours($HID)
{
  // returns the OID associated with the outreach the hours are assigned to
  $OID = dbGetOIDForHours($HID);

  return canApproveHoursForOutreach($OID);
}

/* canApproveHours() - returns whether the user can approve hours for the given outreach.
 */
function canApproveHoursForOutreach($OID)
{
  // has permissions or is editing own outreach
  if(isMyOutreach($OID) || hasPermissionForTeam('approveHours',dbGetTeamForOutreach($OID))){
    return true;
  }

  return false;
}

function hourLogging_menu()
{
  $items['deleteHours/%'] = array(
				  'page callback' => 'deleteHours',
				  'access callback' => 'canEditHours',
				  'access arguments' => array(1,2,3),
				  'page arguments' => array(1,2,3),
				  'type' => MENU_CALLBACK,
				  );
  $items['approveHours/%'] = array(
				  'page callback' => 'approveHours',
				  'page arguments' => array(1),
				  'access callback' => 'canApproveHours',
				  'access arguments' => array(1),
				  'type' => MENU_CALLBACK,
				  );
  return $items;
}



?>