<?php
/**
 * @file
 * This is the main module file.
 */

include_once("outreach.inc");
include_once("/var/www-croma/croma_modules/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $outreachBlockInfo;
global $outreachBlockViewFns;

$outreachBlockInfo = array();
$outreachBlockViewFns = array();

include_once("philipDisplay.php");
include_once("display.php");

/*
  Implements hook_help().
*/
function outreach_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The outreach module manages outreach in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function outreach_block_info()
{
    global $outreachBlockInfo;

    return($outreachBlockInfo);
}

//
// hook in the blocks
//
function outreach_block_view($delta = '')
{
    global $outreachBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$outreachBlockViewFns)) {
      $outreachBlockViewFns[$delta]($block);
    }

    return $block;
}

?>