<?php
/**
 * @file
 * This is the main module file.
 */

include_once("outreach.inc");
$upOne = realpath(dirname(__FILE__) . '/..');
include_once($upOne.'/includePaths.inc');
include_once(MODULES_FOLDER."/blockSupport.php");

// $blockInfo - an array of info that is passed to Drupal
//      when it asks about the module.
//
// $blockViewFns - an array of functions that are called
//      when Drupal calls *_block_view();
//

global $outreachBlockInfo;
global $outreachBlockViewFns;

$outreachBlockInfo = array();
$outreachBlockViewFns = array();

include_once("outreach_display.php");

/*
  Implements hook_help().
*/
function outreach_help($path, $arg) {

  if ($path == 'admin/help#rupalform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The outreach module manages outreach in CROMA.') . '</p>';
    return $output;
  }
}

//
// provide information about the blocks that this module provides
//
function outreach_block_info()
{
    global $outreachBlockInfo;

    return($outreachBlockInfo);
}

//
// hook in the blocks
//
function outreach_block_view($delta = '')
{
    global $outreachBlockViewFns;

    $block = array();

    if(array_key_exists($delta,$outreachBlockViewFns)) {
      $outreachBlockViewFns[$delta]($block);
    }

       return $block;
}

function outreach_menu() {
  $items['approveIdea'] = array(
				  'page callback' => 'approveIdea',
				  'page arguments' => array(1),
				  'access callback' => 'hasPermissionForTeam',
				  'access arguments' => array('approveIdeas', 2), // passes in the TID
				  'type' => MENU_CALLBACK,
				  );

  $items['rejectIdea'] = array(
				  'page callback' => 'rejectIdea',
				  'page arguments' => array(1),
				  'access callback' => 'hasPermissionForTeam',
				  'access arguments' => array('approveIdeas', 2), // passes in the TID
				  'type' => MENU_CALLBACK,
				  );

  $items['deleteTag'] = array(
				  'page callback' => 'deleteTag',
				  'page arguments' => array(1),
				  'access callback' => 'hasPermissionForTeam',
				  'access arguments' => array('manageOutreachTags', 2), // passes in the TID
				  'type' => MENU_CALLBACK,
				  );

  $items['duplicateOutreach'] = array(
				  'page callback' => 'duplicateOutreach',
				  'page arguments' => array(1),
				  'access callback' => 'isMyTeam',
				  'access arguments' => array(2), // passes in the TID
				  'type' => MENU_CALLBACK,
				  );


  $items['cancelOutreach'] = array(
				  'page callback' => 'changeCancel',
				  'page arguments' => array(1),
				  'access callback' => 'isMyTeam',
				  'access arguments' => array(2), // passes in the TID
				  'type' => MENU_CALLBACK,
				  );
  return $items;
}
?>